/**********************************************************
Font generated by the LCD Vision V1.00 font editor
(C) Copyright 2011 Pavel Haiduc, HP InfoTech s.r.l.
http://www.hpinfotech.com

Font name: La Bamba Bold
The font is proportional (has variable width).
Font height: 17 pixels
First character: 0x20
Last character: 0x7F
**********************************************************/

#ifndef _LA_BAMBA17_INCLUDED_
#define _LA_BAMBA17_INCLUDED_

extern flash unsigned char la_bamba17[];

#endif

